Capstone/src/KidSports/Models/Application.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KidSports.Models
{
    public class Application
    {
        public int ApplicationID { get; set; }
        public List<AppStateJoin> StatesLived { get; set; }
        public bool LivedOutsideUSA { get; set; }
        
        public string BackgroundRequest { get; set; }
        // string xml 
        public string BackgroundResult { get; set; }
        // string xml
        public DateTime DOB { get; set; }

        public bool IsHeadCoach { get; set; }
        public bool IsAssistantCoach { get; set; }
        public int YearsLivedInOregon { get; set; }
        public string CurrentEmployer { get; set; }
        public string JobTitle { get; set; }

        public string Address { get; set; }
        public string City { get; set; }
        public State State { get; set; }
        public string ZipCode { get; set; }

        public School AppSchool { get; set; }
        public Sport AppSport { get; set; }
        
        public string NameOfChild { get; set; }
        public int YearsExperience { get; set; }

        public bool HasContacted { get; set; }
        
        public string  DlPath { get; set; }

        public bool PcaIsChecked { get; set; }
        public string PcaPath { get; set; }

        public string PcaVoucherCode { get; set; }

        public bool NfhsIsChecked { get; set; }
        public string NfhsPath { get; set; }

        public string BadgePath { get; set; }

        public string PledgeInitials { get; set; }
        public string PledgeName { get; set; }
        public bool pledgeIsInAgreement { get; set; }
        public DateTime PledgeSubmissionDate { get; set; }
        public DateTime ConcussionCourseSubmissionDate { get; set; }
        public DateTime PcaCourseSubmissionDate { get; set; }
        public List<AppAreaJoin> Areas { get; set; }
        public string AppGender { get; set; }
        public string AppGrade { get;  set; }
        public Area AppArea { get; set; }
        public List<AppExpJoin> PreviousExperience { get; set; }
    }
}

Capstone/src/KidSports/Models/ViewModels/BadgeViewModel.cs
using KidSports.Models;
using Microsoft.AspNetCore.Http;
using System;

namespace KidSports.Models.ViewModels
{
    public class BadgeViewModel
    {
        public string Direction { get; set; }
        public int ApplicationID { get; set; }
        public IFormFile File { get; set; }
        public string BadgePath { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}

Capstone/src/KidSports/Models/ViewModels/CoachInfoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KidSports.Models.ViewModels
{
    public class CoachInfoViewModel
    {
        public string Direction { get; set; }
        public int ApplicationID { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]
        public string FirstName { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]
        public string MiddleName { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]
        public string LastName { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]
        public string PreviousLastName1 { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]
        public string PreviousLastName2 { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]

        public string PreviousLastName3 { get; set; }
        public List<State> AllStates { get; set; }
        [StringLength(20, ErrorMessage = "Name must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "Name must be capitalized and not contain any digits or special characters")]
        public string PreferredName { get; set; }
        [DataType(DataType.Date)]


        //TODO: Validation?? I deleted a commented out piece of validation during merge, unsure if it was important.
        public DateTime? DOB { get; set; }

        public int YearsLivingInOregon { get; set; }
        [StringLength(50, ErrorMessage = "Name must be less than 50 characters")]
        [RegularExpression("[A-za-z0-9 #.-]*$", ErrorMessage ="Invalid Address test")]
        public string Address { get; set; }
        [StringLength(20, ErrorMessage = "City must be less than 20 characters")]
        [RegularExpression("^([A-Z]{1}[a-zA-Z ]*$)", ErrorMessage = "City must be capitalized and not contain any digits or special characters")]

        public string City { get; set; }
        public State State { get; set; }
        public int newPickedStateID { get; set; }
        [RegularExpression("^[0-9]{5}$", ErrorMessage = "Enter Valid 5 digit zipcode")]
        public string Zip { get; set; }
        public List<int> PreviousStates { get; set; }
        public bool HasLivedOutsideUSA { get; set; }
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string AlternatePhone { get; set; }
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string CellPhone { get; set; }

        [StringLength(50, ErrorMessage = "Name must be less than 50 characters")]
        [RegularExpression("^[A-za-z0-9 #.-]*$", ErrorMessage = "Invalid")]
        public string CurrentEmployer { get; set; }
        [StringLength(50, ErrorMessage = "Name must be less than 50 characters")]
        [RegularExpression("^[A-za-z0-9 #.-]*$", ErrorMessage = "Invalid")]
        public string JobTitle { get; set; }
    }
}

Capstone/src/KidSports/Models/ViewModels/ConcussionCourseViewModel.cs
using KidSports.Models;
using Microsoft.AspNetCore.Http;
using System;

namespace KidSports.Models.ViewModels
{
    public class ConcussionCourseViewModel
    {
        public string Direction { get; set; }
        public int ApplicationID { get; set; }
        public string NfhsPath { get; set; }

        public ApplicationStatus ApplicationStatus { get; set; }
        public Nullable<DateTime> ConcussionCourseSubmissionDate { get; set; }
        public IFormFile File { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public AppLink nfhslink { get; set; }
    }
}

Capstone/src/KidSports/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using KidSports.Models.ViewModels;
using KidSports.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using KidSports.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KidSports.Controllers
{
    [Authorize]
    public class ApplicationController : Controller
    {
        private IHostingEnvironment _environment;
        private IApplicationRepo appRepo;
        private IUserRepo userRepo;
        private IStateRepo stateRepo;
        private ISportRepo sportRepo;
        private IAreaRepo areaRepo;
        private ISchoolRepo schoolRepo;
        private IGradeRepo gradeRepo;
        private IExpRepo expRepo;
        private IAppStatusRepo appStatusRepo;

        UserManager<User> userManager;

        public ApplicationController(UserManager<User> UM, IHostingEnvironment environment, IApplicationRepo apprepo, IUserRepo userrepo, IStateRepo staterepo, ISportRepo sportrepo, IAreaRepo arearepo, ISchoolRepo schoolrepo, IGradeRepo graderepo, IExpRepo exprepo, IAppStatusRepo appstatusrepo)
        {
            userManager = UM;
            _environment = environment;
            appRepo = apprepo;
            userRepo = userrepo;
            stateRepo = staterepo;
            sportRepo = sportrepo;
            areaRepo = arearepo;
            schoolRepo = schoolrepo;
            gradeRepo = graderepo;
            expRepo = exprepo;
            appStatusRepo = appstatusrepo;
        }

        #region Home Page
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IndexViewModel ivm = new IndexViewModel();
            User user = await userManager.FindByNameAsync(User.Identity.Name);
            if (user != null)
            {
                user = userRepo.GetDetailedUser(user);
                ivm.UserFirstName = user.FirstName;

                ivm.ApplicationID = 0;
                ivm.ApplicationStatus = new ApplicationStatus();
                ivm.Application = new Application();
                ivm.Application.IsHeadCoach = false;

                if (user.currentYearApp != null)
                {
                    ApplicationStatus appStatus = appStatusRepo.GetAppStatusByID(user.currentYearApp.ApplicationID);
                    DateTime renewalDate = new DateTime(DateTime.Now.Year, 6, 1).AddDays(-90);
                    if (appStatus.AppStartDate < renewalDate)
                    {
                        if (user.UserApplications == null)
                            user.UserApplications = new List<Application>();

                        user.UserApplications.Add(user.currentYearApp);

                        Application renewalApp = new Application();
                        renewalApp = user.currentYearApp;
                        renewalApp.AppGender = null;
                        renewalApp.AppArea = null;
                        renewalApp.AppGrade = null;
                        renewalApp.AppSchool = null;
                        renewalApp.AppSport = null;
                        renewalApp.NfhsPath = null;
                        renewalApp.PledgeInitials = null;
                        renewalApp.PledgeName = null;
                        renewalApp.pledgeIsInAgreement = false;
                        renewalApp.PledgeSubmissionDate = DateTime.Now;
                        renewalApp.YearsLivedInOregon += 1;

                        user.currentYearApp = renewalApp;
                        userRepo.Update(user);

                    } else
                    {
                        ivm.ApplicationStatus = appStatus;
                    }

                    int id = user.currentYearApp.ApplicationID;
                    ivm.ApplicationID = id;
                    ivm.Application = user.currentYearApp;
                    
                    return View(ivm);
                }
            }

            return View(ivm);
        }

        [HttpPost]
        public async Task<IActionResult> Index(IndexViewModel ivm)
        {
            User user = await userManager.FindByNameAsync(User.Identity.Name);
            if (user != null)
            {
                user = userRepo.GetDetailedUser(user);
            }

            if (ivm.ApplicationID == 0)
            {
                Application app = new Application();
                appRepo.CreateApp(app);

                ApplicationStatus appstatus = new ApplicationStatus();
                appstatus.AppStartDate = DateTime.Now;
                appstatus.ApplicationID = app.ApplicationID;
                appStatusRepo.Create(appstatus);

                ivm.ApplicationID = app.ApplicationID;
                if (user != null)
                {
                    user.currentYearApp = app;
                    userRepo.Update(user);
                }
                return RedirectToAction("CoachInfo", new { AppID = ivm.ApplicationID });
            }

            //This will probably need to include all of your past application id's as well. so users can view their own past apps.
            if (user.currentYearApp.ApplicationID == ivm.ApplicationID || User.IsInRole("Admin") || User.IsInRole("SportsManager"))
            {
                if (ivm.ApplicationID != 0)
                {
                    ivm.ApplicationStatus = appStatusRepo.GetAppStatusByID(ivm.ApplicationID);

                    /* Use app id to do stuff */
                    if (ivm.PageName == "Information")
                        return RedirectToAction("CoachInfo", new { AppID = ivm.ApplicationID });
                    if (ivm.PageName == "Interests")
                        return RedirectToAction("CoachInterests", new { AppID = ivm.ApplicationID });
                    if (ivm.PageName == "Pledge")
                        return RedirectToAction("CoachPledge", new { AppID = ivm.ApplicationID });
                    if (ivm.PageName == "NFHS Course")
                        return RedirectToAction("ConcussionCourse", new { AppID = ivm.ApplicationID });
                    if (ivm.PageName == "PCA Course")
                        return RedirectToAction("PcaCourse", new { AppID = ivm.ApplicationID });
                    if (ivm.PageName == "ID")
                        return RedirectToAction("ID", new { AppID = ivm.ApplicationID });
                    if (ivm.PageName == "Badge")
                        return RedirectToAction("Badge", new { AppID = ivm.ApplicationID });
                    return View(ivm);
                }
            }
            else
                return RedirectToAction("AccessDenied", "Account");

            return View(ivm);
        }

        #endregion

        #region SportsManager Views
        [HttpGet]
        [Authorize(Roles = "SportsManager, Admin")]
        public IActionResult Applications()
        {
            //Get the sports manager and put their area in the search model by default.
            ApplicationSearchModel asm = new ApplicationSearchModel();
            asm.filteredApps = new List<Application>();
            asm.filteredUsers = new List<User>();
            asm.filteredAppStatus = new List<ApplicationStatus>();
            asm.filteredGrades = new List<string>();
            asm.filteredSchools = new List<string>();
            asm.filteredSports = new List<string>();
            asm.filteredAreas = new List<string>();
            asm.Grade = new List<int>();
            asm.Sport = new List<int>();
            asm.Area = new List<int>();
            asm.School = new List<int>();


            List<Application> allApps = appRepo.GetAllApplications().ToList();
            List<Application> filteredApps = new List<Application>();
            List<User> filteredUsers = new List<User>();
            List<ApplicationStatus> filteredAppStatus = new List<ApplicationStatus>();

            foreach (Application a in allApps)
            {
                User u = userRepo.GetUserByID(a.ApplicationID);
                if (u != null)
                {
                    filteredApps.Add(a);
                }
            }

            foreach (Application app in filteredApps)
            {
                User u = userRepo.GetUserByID(app.ApplicationID);
                ApplicationStatus appstatus = appStatusRepo.GetAppStatusByID(app.ApplicationID);

                filteredUsers.Add(u);
                filteredAppStatus.Add(appstatus);
                asm.filteredAreas.Add(app.AppArea.AreaName);
                asm.filteredGrades.Add(app.AppGrade);
                asm.filteredSchools.Add(app.AppSchool.SchoolName);
                asm.filteredSports.Add(app.AppSport.SportName);
            }

            if (filteredApps != null)
                asm.filteredApps.AddRange(filteredApps);
            else
                asm.filteredApps = new List<Application>();

            if (filteredUsers != null)
                asm.filteredUsers.AddRange(filteredUsers);
            else
                asm.filteredUsers = new List<User>();

            if (filteredAppStatus != null)
                asm.filteredAppStatus.AddRange(filteredAppStatus);
            else
                asm.filteredAppStatus = new List<ApplicationStatus>();

            asm.allAreas = areaRepo.GetAllAreas();
            asm.allSchools = schoolRepo.GetAllSchools();
            asm.allSports = sportRepo.GetAllSports();
            asm.allGrades = gradeRepo.GetAllGrades();

            return View(asm);
        }

        [HttpPost]
        [Authorize(Roles = "SportsManager, Admin")]
        public IActionResult Applications([FromBody] ApplicationSearchModel asm)
        {
            List<Application> filteredApps = appRepo.GetFilteredApplications(asm).ToList();

Capstone/src/KidSports/Views/Application/Applications.cshtml
@model ApplicationSearchModel
@{
    ViewBag.Title = "Applications";
}

<h2>Application Status Information:</h2>

@*<table class="table table-responsive">
    <thead>
        <tr>
            <td class="bg-success col-xs-3" style="font-weight:bold;">Complete</td>
            <td class="bg-warning col-xs-3" style="font-weight:bold;">Pending Validation</td>
            <td class="bg-danger col-xs-3" style="font-weight:bold;">Incomplete Information</td>
        </tr>
    </thead>
</table>*@

<form asp-action="Applications" asp-controller="Application" method="post">
    <div class="row" style="margin-bottom:10px;">
        <div class="col-md-3">
            <label name="Area" class="control-label">Area:</label>
            <select id="areaFilter" asp-for="Area"
                    asp-items="@(new SelectList(Model.allAreas, "AreaName", "AreaName"))" class="selectpicker form-control" data-size="5" multiple="multiple"></select>
        </div>

        <div class="col-md-3">
            <label name="School" class="control-label">School:</label>
            <select id="schoolFilter" asp-for="School"
                    asp-items="@(new SelectList(Model.allSchools, "SchoolName", "SchoolName"))" class="selectpicker form-control" data-size="5" multiple="multiple"></select>
        </div>

        <div class="col-md-3">
            <label name="Sport" class="control-label">Sport:</label>
            <select id="sportFilter" asp-for="Sport"
                    asp-items="@(new SelectList(Model.allSports, "SportName", "SportName"))" class="selectpicker form-control" data-size="5" multiple="multiple"></select>
        </div>

        <div class="col-md-3">
            <label name="Grade" class="control-label">Grade:</label>
            <select id="gradeFilter" asp-for="Area"
                    asp-items="@(new SelectList(Model.allGrades, "GradeName", "GradeName"))" class="selectpicker form-control" data-size="5" multiple="multiple"></select>
        </div>
    </div>
</form>

<div class="form-group col-xs-offset-1 col-xs-10 col-md-offset-8 col-md-4">
    <input type="hidden" id="system-search" class="form-control glyphicon glyphicon-search" placeholder="Search...">
</div>

<div class="row">
    <table id="myTable" class="table table-responsive table-striped table-list-search">
        <tr>
            <td class=""></td>
            <td class="col-xs-3">Application Details</td>
            <td class="col-xs-3">Applicant Name</td>
            <td class="col-xs-3">Start Date</td>
            <td class="col-xs-3">Completion Date</td>
        </tr>

        @for (int i = 0; i < Model.filteredApps.Count; i++)
        {
            <tr>
                <th><input asp-for="@Model.filteredApps[i].HasContacted" type="checkbox" /></th>
                <td>
                    <a href='@Url.Action("ApplicantDetails", "Application", new { ApplicantID = Model.filteredUsers[i].Id })'>
                        @if (Model.filteredAppStatus[i].AppApprovalDate != null)
                        {
                            <input type="button" class="btn btn-success" value="View Details">
                        } else if (Model.filteredAppStatus[i].AppCompletionDate != null)
                        {
                            <input type="button" class="btn btn-warning" value="View Details">
                        } else
                        {
                            <input type="button" class="btn btn-danger" value="View Details">
                        }
                    </a>
                </td>
                <td> @Html.DisplayFor(modelItem => Model.filteredUsers[i].FirstName) @Html.DisplayFor(modelItem => Model.filteredUsers[i].LastName)</td>
                <td> @Html.DisplayFor(modelItem => Model.filteredAppStatus[i].AppStartDate) </td>
                <td> @Html.DisplayFor(modelItem => Model.filteredAppStatus[i].AppCompletionDate) </td>
                <td style="visibility:hidden; display:none;"> @if (Model.filteredApps[i].AppArea != null) { @Html.DisplayFor(modelItem => Model.filteredApps[i].AppArea.AreaName); }</td>
                <td style="visibility:hidden; display:none;"> @if (Model.filteredApps[i].AppSchool != null) { @Html.DisplayFor(modelItem => Model.filteredApps[i].AppSchool.SchoolName); }</td>
                <td style="visibility:hidden; display:none;"> @if (Model.filteredApps[i].AppSport != null) { @Html.DisplayFor(modelItem => Model.filteredApps[i].AppSport.SportName); }</td>
                <td style="visibility:hidden; display:none;"> @if (Model.filteredApps[i].AppGrade != null) { @Html.DisplayFor(modelItem => Model.filteredApps[i].AppGrade); }</td>
            </tr>
        }
    </table>
</div>

<div class="pull-right" style="margin-top:50px">
    <button type="button" onclick="location = '/Admin/UpdateUser'" class="btn btn-primary btn-md-10">Enter Applicant Manually</button>
</div>	



<script>
    $(document).ready(function () {

        $("select").change(function () {
            $("#system-search").val($(this).val());

            var filterArea = "";
            if ($("#areaFilter").val() != null)
                filterArea = $("#areaFilter").val();

            var filterSchool = "";
            if ($("#schoolFilter").val() != null)
                filterSchool = $("#schoolFilter").val();

            var filterSport = "";
            if ($("#sportFilter").val() != null)
                filterSport = $("#sportFilter").val();

            var filterGrade = "";
            if ($("#gradeFilter").val() != null)
                filterGrade = $("#gradeFilter").val();

            var filter = "";

            if (filterArea != "")
                filter == "" ? filter = filterArea : filter = filter + "," + filterArea;

            if (filterSchool != "")
                filter == "" ? filter = filterSchool : filter = filter + "," + filterSchool;

            if (filterSport != "")
                filter == "" ? filter = filterSport : filter = filter + "," + filterSport;

            if (filterGrade != "")
            filter == "" ? filter = filterGrade : filter = filter + "," + filterGrade;

            $("#system-search").val(filter.toString().toLowerCase());


    var activeSystemClass = $('.list-group-item.active');

       var that = $("#system-search");
        // affect all table rows on in systems table
        var tableBody = $('.table-list-search tbody');
        var tableRowsClass = $('.table-list-search tbody tr');
        $('.search-sf').remove();
        tableRowsClass.each( function(i, val) {

            //Lower text for case insensitive
            var rowText = $(val).text().toLowerCase();
            var inputText = $(that).val().toLowerCase();
            if(inputText != '')
            {
                $('.search-query-sf').remove();
                tableBody.prepend('<tr class="search-query-sf"><td colspan="6"><strong> Searching for: "'+ $(that).val()+ '"</strong></td></tr>');
            }
            else
            {
                $('.search-query-sf').remove();
            }

           
            var multipleInputs = inputText.split(",");
            var display = false;

            //console.log(multipleInputs);
            for (var filter = 0; filter < multipleInputs.length; filter++)
            {
                console.log(rowText.indexOf(multipleInputs[filter]));
                console.log(multipleInputs[filter]);
                if (rowText.indexOf(multipleInputs[filter]) != -1 && (multipleInputs[filter] != "" || multipleInputs[filter] != null || multipleInputs[filter] != " "))
                    display = true; 
            }
          
            //console.log(display);
            //console.log(tableRowsClass.eq(i));
            if(display == false && filter != "")
            {
                tableRowsClass.eq(i).hide();
            } 
            else
            {
                $('.search-sf').remove();
                tableRowsClass.eq(i).show();
            }
           
        });
        //all tr elements are hidden
        if(tableRowsClass.children(':visible').length == 0)
        {
            tableBody.append('<tr class="search-sf"><td class="text-muted" colspan="6">No entries found.</td></tr>');
        }
   }).change();
});
</script>

Capstone/src/KidSports/Views/Application/ApproveDeny.cshtml
<div class="btn-group col-xs-12 col-sm-3">
    <button type="submit" name="Direction" value="approve" class="btn btn-success col-xs-12">Approve </button>
</div>
<div class="btn-group col-xs-12 col-sm-3">
    <button type="submit" name="Direction" value="deny" class="btn btn-danger col-xs-12">Deny</button>
</div>

Capstone/src/KidSports/Views/Application/Badge.cshtml
@model BadgeViewModel
@{
    ViewBag.Title = "Badge";
}



<h1 class="text-center">Coach ID Badge</h1>
<form asp-controller="Application" asp-action="Badge" method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="@Model.ApplicationID" value="@Model.ApplicationID" />
    <input asp-for="BadgePath" type="hidden" />
    <div class="well">
        <div class="row">
            <div class="form-group col-xs-offset-1 col-md-offset-0 col-xs-10 col-md-12">
                <p>
                    Once you have completed the necessary requirements and have been approved by a KidSports Sports Manager-
                    you are required to obtain your KS Coach ID Badge.
                    <Strong>This card is required to be worn and visible for all games.</Strong>
                </p>
            </div>
        </div>
        <div class="row" style="margin-top:20px">
            <div class="form-group col-xs-offset-1 col-xs-10 col-md-6">
                <div style="text-align:left;">
                    <strong>Image Requirements:</strong>
                    <ul>
                        <li>Mininum 8 mega pixel resolution</li>
                        <li>No Hats or Sunglasses</li>
                        <li>An individual photo</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="form-group col-xs-offset-1 col-md-offset-0 col-xs-10 col-md-4">
                <label for="" class="control-label">Upload Photo</label>
                <input type="file" asp-for="File"
                       class="borrowerImageFile" data-errormsg="PhotoUploadErrorMsg">
            </div>
            <div class="form-group col-xs-offset-1 col-md-offset-0 col-xs-10 col-md-4">
                @if (Model.BadgePath != null && Model.BadgePath.Contains(".pdf"))
                {
                    <embed src="@Model.BadgePath" data-type="pdf" class="img-thumbnail" />

                }
                else
                {
                    <img src="@Model.BadgePath" class="img-thumbnail" />
                }
            </div>

        </div>
        @if ((Model.BadgePath != null && Model.BadgePath != "") && (User.IsInRole("SportsManager") || User.IsInRole("Admin")))
            {
            <div class="row">
                <div class="form-group col-xs-offset-1 col-md-offset-4 col-xs-10 col-md-4">
                    <a href="@Model.BadgePath" type="button" class="btn btn-default" download>Download</a>
                </div>

            </div>
        }

    </div>


    @if (User.IsInRole("SportsManager") || User.IsInRole("Admin"))
    {
        <div class="btn-group col-xs-12 col-sm-3">
            <button type="submit" name="Direction" value="previous" class="btn btn-primary col-xs-12 pull-left"> <i class="fa fa-arrow-left" aria-hidden='true'></i>  Previous</button>
        </div>

        Html.RenderPartial("ApproveDeny.cshtml");

        <div class="btn-group col-xs-12 col-sm-3">
            <button type="submit" name="Direction" value="next" class="btn btn-primary col-xs-12 pull-right"><i class="fa fa-flag-checkered" aria-hidden='true'></i> Finish</button>
        </div>
    }
    else
    {
        <div class="btn-group col-xs-12 col-sm-3">
            <button type="submit" name="Direction" value="previous" class="btn btn-primary col-xs-12 pull-left"> <i class="fa fa-arrow-left" aria-hidden='true'></i>  Previous</button>
        </div>

        <div class="col-sm-6"></div>

        <div class="btn-group col-xs-12 col-sm-3">
            <button type="submit" name="Direction" value="next" class="btn btn-primary col-xs-12 pull-right"><i class="fa fa-flag-checkered" aria-hidden='true'></i> Finish</button>
        </div>
    }
</form>